const FLAGS: Record<string, string> = {
  France: '🇫🇷',
  Brazil: '🇧🇷',
  Cameroon: '🇨🇲',
  'Ivory Coast': '🇨🇮',
  Argentina: '🇦🇷',
  Portugal: '🇵🇹',
  Algeria: '🇩🇿',
  Belgium: '🇧🇪',
  Mali: '🇲🇱',
  'Czech Republic': '🇨🇿',
  Switzerland: '🇨🇭',
  Italy: '🇮🇹',
  Croatia: '🇭🇷',
  Netherlands: '🇳🇱',
  Senegal: '🇸🇳',
  Ghana: '🇬🇭',
  Serbia: '🇷🇸',
  Slovakia: '🇸🇰',
  Angola: '🇦🇴',
  Sweden: '🇸🇪',
  Norway: '🇳🇴',
  'Burkina Faso': '🇧🇫',
  Zimbabwe: '🇿🇼',
  Georgia: '🇬🇪',
  Uruguay: '🇺🇾',
  'United States': '🇺🇸',
  England: '🏴',
  'Dominican Republic': '🇩🇴',
  'Bosnia and Herzegovina': '🇧🇦',
  Spain: '🇪🇸',
  Germany: '🇩🇪',
  Turkey: '🇹🇷',
  Denmark: '🇩🇰',
  Romania: '🇷🇴',
  Nigeria: '🇳🇬',
  Morocco: '🇲🇦',
  Tunisia: '🇹🇳',
  Guinea: '🇬🇳',
  'DR Congo': '🇨🇩',
  Congo: '🇨🇬',
  Gabon: '🇬🇦',
  Benin: '🇧🇯',
  Togo: '🇹🇬',
  Madagascar: '🇲🇬',
  Poland: '🇵🇱',
  Austria: '🇦🇹',
  Ukraine: '🇺🇦',
  Wales: '🏴',
  Scotland: '🏴',
  Colombia: '🇨🇴',
  Chile: '🇨🇱',
  Ecuador: '🇪🇨',
  Qatar: '🇶🇦',
  Japan: '🇯🇵',
  'South Korea': '🇰🇷',
}

export function flagFor(nationality: string): string {
  return FLAGS[nationality] ?? '🏳️'
}
